require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lifts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Lift. As you add validations to Lift, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Lift.create! valid_attributes
      get lifts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lift = Lift.create! valid_attributes
      get lift_url(lift)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lift_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      lift = Lift.create! valid_attributes
      get edit_lift_url(lift)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Lift" do
        expect {
          post lifts_url, params: { lift: valid_attributes }
        }.to change(Lift, :count).by(1)
      end

      it "redirects to the created lift" do
        post lifts_url, params: { lift: valid_attributes }
        expect(response).to redirect_to(lift_url(Lift.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Lift" do
        expect {
          post lifts_url, params: { lift: invalid_attributes }
        }.to change(Lift, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post lifts_url, params: { lift: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lift" do
        lift = Lift.create! valid_attributes
        patch lift_url(lift), params: { lift: new_attributes }
        lift.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lift" do
        lift = Lift.create! valid_attributes
        patch lift_url(lift), params: { lift: new_attributes }
        lift.reload
        expect(response).to redirect_to(lift_url(lift))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        lift = Lift.create! valid_attributes
        patch lift_url(lift), params: { lift: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lift" do
      lift = Lift.create! valid_attributes
      expect {
        delete lift_url(lift)
      }.to change(Lift, :count).by(-1)
    end

    it "redirects to the lifts list" do
      lift = Lift.create! valid_attributes
      delete lift_url(lift)
      expect(response).to redirect_to(lifts_url)
    end
  end
end
